(function () {
  "use strict";

  window.GameData = {
    constants: {
      maxStages: 10,
      stageClearDelay: 1.8,
      victoryDelay: 1.8,
      playerRadius: 18,
      pickupRadius: 7,
      maxPlayerProjectiles: 780,
      maxEnemyProjectiles: 560,
      maxEnemies: 300,
    },
    weapons: {
      cannon: {
        id: "cannon",
        name: "脉冲机炮",
        color: "#5ee2ff",
        baseDamage: 12,
        baseInterval: 0.24,
        projectileSpeed: 720,
      },
      missile: {
        id: "missile",
        name: "散射导弹",
        color: "#ffcf5a",
        baseDamage: 30,
        baseInterval: 1.12,
        projectileSpeed: 430,
        blastRadius: 58,
      },
      drone: {
        id: "drone",
        name: "僚机编队",
        color: "#78f09a",
        baseDamage: 9,
        baseInterval: 0.58,
        projectileSpeed: 620,
      },
      arc: {
        id: "arc",
        name: "连锁电弧",
        color: "#b98cff",
      },
    },
    enemies: {
      chaser: {
        id: "chaser",
        name: "追踪小机",
        hp: 18,
        speed: 105,
        radius: 15,
        damage: 10,
        xp: 7,
        score: 10,
        color: "#ff6b6b",
        behavior: "chase",
      },
      strafe: {
        id: "strafe",
        name: "穿梭机",
        hp: 16,
        speed: 170,
        radius: 13,
        damage: 12,
        xp: 8,
        score: 14,
        color: "#ffcf5a",
        behavior: "strafe",
      },
      shooter: {
        id: "shooter",
        name: "炮艇",
        hp: 34,
        speed: 72,
        radius: 18,
        damage: 11,
        xp: 13,
        score: 24,
        color: "#b98cff",
        behavior: "shooter",
      },
      splitter: {
        id: "splitter",
        name: "分裂机",
        hp: 44,
        speed: 82,
        radius: 21,
        damage: 13,
        xp: 18,
        score: 34,
        color: "#78f09a",
        behavior: "splitter",
      },
      armored: {
        id: "armored",
        name: "装甲机",
        hp: 96,
        speed: 54,
        radius: 25,
        damage: 17,
        xp: 24,
        score: 52,
        color: "#f6f7fb",
        behavior: "armored",
      },
      boss: {
        id: "boss",
        name: "深空母舰",
        hp: 540000,
        speed: 58,
        radius: 58,
        damage: 21,
        xp: 260,
        score: 1500,
        color: "#ff6b6b",
        behavior: "boss",
      },
    },
  };
})();
